name: practica19
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <34.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  pdf: ^3.6.2
  path_provider: ^2.0.5
  printing: ^5.6.2
  flutter_file_downloader: ^1.1.4
  #image_downloader: ^0.31.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
